name: Rust
on:
  push:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: default
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Generate documentation
        run: time cargo doc --no-deps --all-features --release --quiet
  deploy_documentation:
    needs: build_documentation
    name: Deploy documentation to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  apply_suggestions:
    name: Format code, apply compiler suggestions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustfmt
        profile: minimal
    - name: Format
      run: cargo fmt
    - name: Apply compiler suggestions
      run: |
        cargo fix --all-features --edition --edition-idioms
        cargo clippy --fix -Z unstable-options
    - name: Commit changes to code, if any
      run: |
        git config --global user.name 'Emil Sayahi'
        git config --global user.email 'emmyoh@users.noreply.github.com'
        git diff --quiet && git diff --staged --quiet || git commit -am "chore: Format and apply compiler suggestions."
        git push
